# Generated by Django 5.2.1 on 2025-05-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the ingredient", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the recipe", max_length=100),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        help_text="List of ingredients used in the recipe",
                        related_name="recipes",
                        to="recipe_management.ingredient",
                    ),
                ),
            ],
        ),
    ]
